drivers: gpu: dsi_display: remove unused variables
../drivers/gpu/drm/msm/dsi-staging/dsi_display.c:8191:27: error: unused variable 'cur_mode' [-Werror,-Wunused-variable]
        struct dsi_display_mode *cur_mode = NULL;
                                 ^
../drivers/gpu/drm/msm/dsi-staging/dsi_display.c:8189:6: error: unused variable 'count' [-Werror,-Wunused-variable]
        u32 count = 0;
            ^
../drivers/gpu/drm/msm/dsi-staging/dsi_display.c:8190:6: error: unused variable 'rc' [-Werror,-Wunused-variable]
        int rc = 0;
            ^
3 errors generated.

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>